# @name /api/first-service/public-resource - without Access Token
GET {{firstServiceUrl}}/api/first-service/public-resource

###

# @name /api/first-service/private-resource - without Access Token
GET {{firstServiceUrl}}/api/first-service/private-resource

###

# @name /api/first-service/private-resource - with Access Token
GET {{firstServiceUrl}}/api/first-service/private-resource
Authorization: Bearer {{access_token}}

###
# @name /api/first-service/private-resource-role-protected
GET {{firstServiceUrl}}/api/first-service/private-resource-role-protected
Authorization: Bearer {{access_token}}

###
# @name /api/first-service/private-resource-scope-protected
GET {{firstServiceUrl}}/api/first-service/private-resource-scope-protected
Authorization: Bearer {{access_token}}
