# @name /api/second-service/call-first-service-pass-token
GET {{secondServiceUrl}}/api/second-service/call-first-service-pass-token
Authorization: Bearer {{access_token}}

###
# @name /api/second-service/call-first-service-as-service-client
GET {{secondServiceUrl}}/api/second-service/call-first-service-as-service-client
Authorization: Bearer {{access_token}}