version: '3.9'

services:
  postgres:
    container_name: altimeet-postgres
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      - altimeet-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycloak:
    container_name: altimeet-keycloak
    image: quay.io/keycloak/keycloak:19.0.3-legacy
    ports:
      - "9990:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: keycloak
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  altimeet-data:
    driver: local
